#!/bin/sh
# . "$(dirname "$0")/_/husky.sh"

# node ".husky/scripts/index.js" $GIT_AUTHOR_NAME $GIT_HTTP_LOW_SPEED_LIMIT

# echo "$(dirname "$0")"

yarn eslint "src/**/*.js"

echo $GIT_EDITOR

yarn prettier --write "src/**/*.js" 

git add .

