#!/bin/sh
# . "$(dirname "$0")/_/husky.sh"

node ".husky/scripts/index.js" $GIT_AUTHOR_NAME

# yarn prettier --write "src/**/*.js" 

# git add .

# yarn eslint "src/**/*.js"

# yarn commitlint -e $HUSKY_GIT_PARAMS